### PR TITLE
fix image source in  deploy.yaml

### PR DESCRIPTION
**Pull request by omerbensaadon**
quay.io does not work! This does though

### CODE REVIEW

**Comment by ruromero** [comment]
What do you mean by _quay.io does not work!_ ?
It does for me. Besides, the image from docker.io has not been updated for over a year.

**Comment by omerbensaadon** [comment]
I ran this with the quay.io image and there was an issue where the window for CloudEvents Player would just go completely blank after flashing the loaded app for a second... 

I'm not really sure I understand why this happens, but I ran the exact same configuration with the ruromero image and everything worked as expected...

**Comment by ruromero** [comment]
Hey @omerbensaadon would you mind sharing the deployment you are using and check for the pod logs in case there is any error?
This error used to happen when the broker was not properly configured so maybe you're not using the right properties or maybe you found another error.
Thanks in advance

**Comment by omerbensaadon** [comment]
```
    apiVersion: serving.knative.dev/v1
    kind: Service
    metadata:
      name: cloudevents-player
    spec:
      template:
        metadata:
          annotations:
            autoscaling.knative.dev/minScale: "1"
        spec:
          containers:
            - image: //the quay.io image
              env:
                - name: BROKER_URL
                  value: http://broker-ingress.knative-eventing.svc.cluster.local/default/example-broker
```

Ah, that makes sense. What am I doing wrong here then?

**Comment by ruromero** [comment]
Uhm this is the old configuration property where you could get this white screen. Try to use this deployment instead https://github.com/ruromero/cloudevents-player/blob/main/src/main/knative/deploy.yaml#L1-L17

By using the `PLAYER_BROKER` environment variable, the broker will set up this endpoint for you using the namespace where it is deployed and the name of the broker, `example-broker` in your case.

I guess the problem you're having (check the logs if you can/want) is that the endpoint `http://broker-ingress.knative-eventing.svc.cluster.local/default/default` where the second `default` is the default name of the broker does not exist and then it cannot connect.

Take a look at this last part of the readme https://github.com/ruromero/cloudevents-player#configuration

**Pull request closed without merging**
